### ISSUE TITLE
Windows 10?

### ISSUE THREAD

**Issue by pythonBerg** [machinalis/iepy#110]
I know install docs are ubuntu focused. Does this explicitly mean windows 10 is not supported? I have been using Stanford NLP and virtually all other prereqs and pip did install correctly. Running anything from binary iepy is problematic with errors ranging from non-standard required appdata directories to access denied errors.  Is anyone using windows or should I just move everything over to my linux vm?

**Comment by jmansilla** [comment]
Havent tested iepy inside windows. If you can collect some guidelines based on your experience, or report the issues, maybe someone can help here.

**Comment by erumharis** [comment]
I am working on iepy in Widows 10 env. The whole installation process is quite hard and requires troubleshooting a variety of errors.. exhasuting, but will let one understand a lot of issues and respective resolutions.. l managed to install iepy  but now stuck at pre-processing the database.The system is giving following error:
  Traceback (most recent call last):
  File "scripts\test2\bin\preprocess.py", line 88, in <module>
    start_preprocess(all_docs, increment_ner)
  File "scripts\test2\bin\preprocess.py", line 39, in start_preprocess
    StanfordPreprocess(increment_ner),
  File "C:\Users\Erum\AppData\Local\Programs\Python\Python35-32\lib\site-packages\iepy\preprocess\stanford_preprocess.py", line 84, in __init__
    self.corenlp = corenlp.get_analizer(gazettes_filepath=gazettes_filepath)
  File "C:\Users\Erum\AppData\Local\Programs\Python\Python35-32\lib\site-packages\iepy\preprocess\corenlp.py", line 56, in get_analizer
    return StanfordCoreNLP(*args, **kwargs)
  File "C:\Users\Erum\AppData\Local\Programs\Python\Python35-32\lib\site-packages\iepy\preprocess\corenlp.py", line 67, in __init__
    self._start_proc()
  File "C:\Users\Erum\AppData\Local\Programs\Python\Python35-32\lib\site-packages\iepy\preprocess\corenlp.py", line 75, in _start_proc
    cwd=_FOLDER_PATH
  File "C:\Users\Erum\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Erum\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

Any help would be highly appreciated. Thanks.

**Comment by Ravi-Rao26** [comment]
Even I have installed IEPY on windows 10 and have got this error and unfortunately its a show stopper .  The program tries to execute .sh file which is not a windows executable.  Then I set up a virtual environment (Virtual Box) in my laptop , installed Ubuntu and then set up python (3.5.2) & IEPY. Everything worked fine

**Comment by erumharis** [comment]
I found a relatively quicker solution, just need to download corenlp.bat file from the Internet (it is an equivalent of the corenlp.sh file for Windows), then copy the file in IEPY's 3rd party tools folder. Finally,
replace the file name corenlp.sh with corenlp.bat inside the python script "corenlp.py".

**Comment by jmansilla** [comment]
@erumharis thanks for the tip.
PR are welcomed.

**Comment by erumharis** [comment]
@jmansilla Welcome. Sorry l could not get what "PR" stands for.

**Comment by jmansilla** [comment]
Pull Requests, with the changes to made to the code, so it can be incorporated

**Comment by erumharis** [comment]
Oh okay. Thank you.
