### ISSUE TITLE
ValueError: There's no IEPY instance on the provided path bin/csv_to_iepy.py

### ISSUE THREAD

**Issue by alonsopg** [machinalis/iepy#128]
Which is the correct way of loading data to iepy?. I tried to:
In:
`
user@MacBook-Pro-de-User:~/Jupyter/iepy_tutorial/iepy_tutorial$ python3 bin/csv_to_iepy.py /Users/user/Jupyter/iepy_tutorial/data.csv`

Out:
```
Traceback (most recent call last):
  File "bin/csv_to_iepy.py", line 21, in <module>
    iepy.setup(__file__)
  File "/usr/local/lib/python3.6/site-packages/iepy/__init__.py", line 37, in setup
    path, project_name, old = _actual_path(fuzzy_path)
  File "/usr/local/lib/python3.6/site-packages/iepy/__init__.py", line 97, in _actual_path
    raise ValueError("There's no IEPY instance on the provided path {}".format(original))
ValueError: There's no IEPY instance on the provided path bin/csv_to_iepy.py
```

My data is a .csv file which look like this:

```
document_id,document_text
TST1-MUC3-0001.txt,TST1-MUC3-0001 TST1-MUC3-0001 GUATEMALA CITY, 4 FEB 90 (ACAN-EFE) -- [TEXT] THE GUATEMALA ARMY DENIED TODAY THAT GUERRILLAS ATTACKED THE SANTO TOMAS PRESIDENTIAL FARM
```

**Comment by ghost** [comment]
This should not be closed, i just cloned this repositoy and I have the same issue

`ValueError: There's no IEPY instance on the provided path instance/csv_to_iepy.py`

The documentation references a `bin` folder, but that does not exist.
