### ISSUE TITLE
The 'appdirs==1.2.0' distribution was not found and is required by iepy

### ISSUE THREAD

**Issue by ramonrod** [machinalis/iepy#131]
Hi Folks,

I would like to try iepy for some relation extraction tasks. I'm having problems installing iepy. I have installed _appdirs==1.4.3_, I also tried to install _appdirs==1.2.0_ from the source, but the system still installs version 1.4.3.

I managed to installed iep in my pc, but every time I run iepy I get the error message:
_pkg_resources.DistributionNotFound: The _appdirs==1.2.0 distribution was not found and is required by iepy_

Is there a solution for this at the moment, it seems iepy doesn't work with the latest version of appdirs, but I cannot get the older version installed on my computer.

My environment:
Win7 64bit
Python 3.6

Thanks for any help,
Ramon

**Comment by jmansilla** [comment]
Hi

I just checked that appdirs 1.2.0 seems to be available: https://pypi.python.org/pypi/appdirs/1.2.0
Can you create a virtualenv and run in a terminal this:
`pip install appdirs==1.2.0`

I just did and installed correctly

**Comment by ramonrod** [comment]
Hi,

Thanks for your reply, I was indeed able to install appdirs==1.2.0

_$ pip show appdirs
Name: appdirs
Version: 1.2.0
Summary: A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
Home-page: http://github.com/ActiveState/appdirs
Author: Trent Mick; Sridhar Ratnakumar
Author-email: trentm@gmail.com; github@srid.name
License: MIT
Location: c:\python36\lib\site-packages_

Now I am getting some other curious error when I run iepy. I am runig the command with administrator rights. What am I doing wrong here?

 _$ iepy
c:\python36\lib\site-packages\sklearn\utils\fixes.py:55: DeprecationWarning: inspect.getargspec() is deprecatuse inspect.signature() or inspect.getfullargspec()
  if 'order' in inspect.getargspec(np.copy)[0]:
Traceback (most recent call last):
  File "C:\Python36\Scripts\iepy-script.py", line 11, in <module>
    load_entry_point('iepy==0.9.6', 'console_scripts', 'iepy')()
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2302, in load
    return self.resolve()
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python36\lib\site-packages\iepy-0.9.6-py3.6.egg\iepy\instantiation\command_line.py", line 27, in <le>
    from iepy.preprocess.corenlp import download as download_corenlp
  File "c:\python36\lib\site-packages\iepy-0.9.6-py3.6.egg\iepy\preprocess\corenlp.py", line 28, in <module>
    JAVA_VERSION = detect_java_version()
  File "c:\python36\lib\site-packages\iepy-0.9.6-py3.6.egg\iepy\preprocess\corenlp.py", line 24, in detect_jaersion
    jversion = subprocess.check_output([java_cmd, "-jar", jar], stderr=subprocess.PIPE)
  File "C:\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access is denied_
