### ISSUE TITLE
Error downloading third party data

### ISSUE THREAD

**Issue by jmansilla** [machinalis/iepy#19]
javier@my_computer:~/repo$ python scripts/download_third_party_data.py
Downloading third party software...
Downloading punkt tokenizer
[nltk_data] Downloading package 'punkt' to /home/javier/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
Downloading wordnet
[nltk_data] Downloading package 'wordnet' to /home/javier/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
Traceback (most recent call last):
  File "scripts/download_third_party_data.py", line 17, in <module>
    download_third_party_data()
  File "scripts/download_third_party_data.py", line 11, in download_third_party_data
    download_tagger()
  File "/home/javier/repo/iepy/tagger.py", line 67, in download
    os.mkdir(DIRS.user_data_dir)
OSError: [Errno 2] No such file or directory: '/home/javier/.config/iepy'

**Comment by eromoe** [comment]
@jmansilla 

```
root@f5dbe915d605:/# iepy --download-third-party-data
/usr/local/lib/python3.5/dist-packages/sklearn/utils/fixes.py:55: DeprecationWarning: inspect.getargspec() is         deprecated, use inspect.signature() instead
  if 'order' in inspect.getargspec(np.copy)[0]:
Traceback (most recent call last):
  File "/usr/local/bin/iepy", line 7, in <module>
    from iepy.instantiation.command_line import execute_from_command_line
  File "/usr/local/lib/python3.5/dist-packages/iepy/instantiation/command_line.py", line 25, in <module>
    from iepy.instantiation.instance_admin import InstanceManager
  File "/usr/local/lib/python3.5/dist-packages/iepy/instantiation/instance_admin.py", line 11, in <module>
    from iepy import defaults
  File "/usr/local/lib/python3.5/dist-packages/iepy/defaults.py", line 3, in <module>
    from iepy.utils import make_feature_list
  File "/usr/local/lib/python3.5/dist-packages/iepy/utils.py", line 19, in <module>
    os.mkdir(DIRS.user_data_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/iepy'
```

Have to `mkdir /root/.config` first

**Comment by jmansilla** [comment]
Yes, it does indeed looks like a bug.

Non related, but probably using iepy with a regular user instead of root (the recommended) this bug wont bite you.
