### ISSUE TITLE
Cannot start core without candidate evidence

### ISSUE THREAD

**Issue by LaundroMat** [machinalis/iepy#41]
Hi, 

I'm interested in the whole subject matter of iepy, but the vocabulary and theories attached to NLP are very new to me. My apologies if what I'm asking shows a complete lack of understanding.

I've installed iepy, and created a simple .csv file and imported it:

```
$ python bin/csv_to_iepy.py docs.csv 

Importing Documents to IEPY from docs.csv
Added 1 documents
Added 2 documents
```

Then preprocessed:

```
$ python bin/preprocess.py

Starting preprocessing step <iepy.preprocess.stanford_preprocess.StanfordPreprocess object at 0x7ff43878ce90>
Loading StanfordCoreNLP...
    Done for 1 documents
    Done for 2 documents
Starting preprocessing step <iepy.preprocess.segmenter.SyntacticSegmenterRunner object at 0x7ff43878cf90>
About to set 1 segments for current doc
New 1 segments created
    Done for 1 documents
About to set 1 segments for current doc
New 1 segments created
    Done for 2 documents
```

Using the web interface, I created a relation called `rvb` and an entity kind Èntity` (to which the relation is attached to, left and right).

If I then run 

```
$  python bin/iepy_runner.py rvb
```

I get

```
Loading candidate evidence from database...
Getting labels from DB
Sorting labels them by evidence
Labels conflict solving
Traceback (most recent call last):
    File "bin/iepy_runner.py", line 71, in <module>
        performance_tradeoff=tuning_mode)
    File "/home/mathieu/dev/iepy-test/lib/python3.3/site-packages/iepy/extraction/active_learning_core.py", line 48, in __init__
    self._setup_labeled_evidences(labeled_evidences)
  File "/home/mathieu/dev/iepy-test/lib/python3.3/site-packages/iepy/extraction/active_learning_core.py", line 162, in _setup_labeled_evidences
    raise ValueError("Cannot start core without candidate evidence")
ValueError: Cannot start core without candidate evidence
```

As I said, this is probably due to my complete lack of understanding of the theories behind IEPY, but how can I create candidate evidence?

**Comment by swu038** [comment]
Hi! 

How about if you defined the relation using entities you created from the gazettes resolution? Thanks!
