### ISSUE TITLE
java error when trying to runany iepy command

### ISSUE THREAD

**Issue by jmansilla** [machinalis/iepy#76]
```
(scipyla)jmansilla@altair:~$ iepy -h
Traceback (most recent call last):
  File "/home/jmansilla/.virtualenvs/scipyla/bin/iepy", line 9, in <module>
    load_entry_point('iepy==0.9.4', 'console_scripts', 'iepy')()
  File "/home/jmansilla/.virtualenvs/scipyla/lib/python3.4/site-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/jmansilla/.virtualenvs/scipyla/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/home/jmansilla/.virtualenvs/scipyla/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/home/jmansilla/.virtualenvs/scipyla/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jmansilla/.virtualenvs/scipyla/lib/python3.4/site-packages/iepy/instantiation/command_line.py", line 27, in <module>
    from iepy.preprocess.corenlp import download as download_corenlp
  File "/home/jmansilla/.virtualenvs/scipyla/lib/python3.4/site-packages/iepy/preprocess/corenlp.py", line 28, in <module>
    JAVA_VERSION = detect_java_version()
  File "/home/jmansilla/.virtualenvs/scipyla/lib/python3.4/site-packages/iepy/preprocess/corenlp.py", line 25, in detect_java_version
    return int(jversion.strip())
ValueError: invalid literal for int() with base 10: b'Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar \n8'
```

**Comment by Brayden-Arthur** [comment]
(limo) limo@limo-ubuntu:~/limo$ iepy -h
Traceback (most recent call last):
  File "/home/limo/limo/bin/iepy", line 9, in <module>
    load_entry_point('iepy==0.9.4', 'console_scripts', 'iepy')()
  File "/home/limo/limo/lib/python3.4/site-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/limo/limo/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/home/limo/limo/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/home/limo/limo/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/limo/limo/lib/python3.4/site-packages/iepy/instantiation/command_line.py", line 27, in <module>
    from iepy.preprocess.corenlp import download as download_corenlp
  File "/home/limo/limo/lib/python3.4/site-packages/iepy/preprocess/corenlp.py", line 28, in <module>
    JAVA_VERSION = detect_java_version()
  File "/home/limo/limo/lib/python3.4/site-packages/iepy/preprocess/corenlp.py", line 25, in detect_java_version
    return int(jversion.strip())
ValueError: invalid literal for int() with base 10: b'Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar \n7'
Also having this issue
