### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by kevin1515** [machinalis/iepy#86]
running on Ubuntu 15.04. Have the following errors. Tried to upgrade package of six, does not work.

(myevn) osboxes@osboxes:~/myevn/test$ iepy
Traceback (most recent call last):
  File "/home/osboxes/myevn/lib/python3.4/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    ws.require(__requires__)
  File "/home/osboxes/myevn/lib/python3.4/site-packages/pkg_resources/__init__.py", line 920, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/osboxes/myevn/lib/python3.4/site-packages/pkg_resources/__init__.py", line 812, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.5.2 (/home/osboxes/myevn/lib/python3.4/site-packages), Requirement.parse('six>=1.7'), {'mock'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/osboxes/myevn/bin/iepy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/osboxes/myevn/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3020, in <module>
    working_set = WorkingSet._build_master()
  File "/home/osboxes/myevn/lib/python3.4/site-packages/pkg_resources/__init__.py", line 616, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/osboxes/myevn/lib/python3.4/site-packages/pkg_resources/__init__.py", line 629, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/osboxes/myevn/lib/python3.4/site-packages/pkg_resources/__init__.py", line 812, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.5.2 (/home/osboxes/myevn/lib/python3.4/site-packages), Requirement.parse('six>=1.7'), {'mock'})

**Comment by cyberyu** [comment]
Same issue here,  first tried with pip install (Python 2.7)

sudo pip install iepy==0.9.4

leads to the error:

Collecting iepy==0.9.4
  Downloading iepy-0.9.4.tar.gz (556kB)
    100% |████████████████████████████████| 557kB 371kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-K1_2ph/iepy/setup.py", line 7, in <module>
        with open(path.join(HERE, 'README.rst'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-K1_2ph/iepy



Then tried with with   

sudo pip3 install iepy==0.9.4

and installation did finish, and the library and Django project files are installed.  But the iepy command cannot be executed, having the same error as kevin1515 mentioned.

**Comment by jiffies** [comment]
Running use python3 and in a virtualenv could figure it out.But I encounter another problem just post in new issue.

**Comment by fiannuzzi** [comment]
Hello everyone, same issue here. I am on Ubuntu 15.04 and followed the instructions here: http://iepy.readthedocs.org/en/latest/installation.html 

**When running iepy --download-third-party-data I get:**

Traceback (most recent call last):
  File "/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 612, in _build_master
    ws.require(__requires__)
  File "/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 810, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.5.2 (/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages), Requirement.parse('six>=1.7'), {'mock'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/francesca/PY_VIRTUALENV/bin/iepy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 810, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.5.2 (/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages), Requirement.parse('six>=1.7'), {'mock'})

**If I upgrade "six' (to v 1.10.0) I get:**

Traceback (most recent call last):
  File "/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 612, in _build_master
    ws.require(__requires__)
  File "/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 810, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.10.0 (/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages), Requirement.parse('six==1.5.2'), {'django-extra-views', 'iepy'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/francesca/PY_VIRTUALENV/bin/iepy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/francesca/PY_VIRTUALENV/lib/python3.4/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: six==1.5.2

Thanks in advance for your help.

**Comment by sbriglie** [comment]
Hi! I was also experiencing this issue and I was able to find a workaround. After some digging around in the virtualenv I established that the issue was that iepy requires (through pip at least) six==1.5.2. Featureforge, another dependence, requires mock, whose latest version, 1.3.0, requires six>=1.7, causing the conflict. The workaround is 
pip uninstall mock
and
pip install mock==1.1.0
This earlier version does not put any version requirements on six, just its presence. The intermediate version 1.2.0 instead requires six>=1.7 and so does not solve the conflict.
Hope this helps!

**Comment by fiannuzzi** [comment]
That worked for me! Thank you sbriglie!

**Comment by delgesu1745** [comment]
Hi all, 

I'm receiving the follow error message.  Seems to be related to what sbriglie and other are discussing here.  Can anyone help point me in the right direction for how to fix?  I'm running Ubuntu 14.04 inside of a Docker container on a Macbook Pro machine.  I was able to install all IEPY dependencies, Java, etc, but get hung up with the error below when I try to pip install IEPY itself.  I'm wondering if it could somehow be connected to the fact that python 3 and pip does not work when calling just $ python or pip.  I need to specify python3 and pip3 for everything.  I've tried creating an alias, but it doesn't seem to resolve the problem.  I've also installed mock 1.1.0 as sbriglie suggests above and it doesn't seem to fix either.  Thanks in advance for any and all help!

Downloading/unpacking featureforge==0.1.5 (from iepy)
  Downloading featureforge-0.1.5.tar.gz
  Running setup.py (path:/tmp/pip_build_root/featureforge/setup.py) egg_info for package featureforge
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/featureforge/setup.py", line 11, in <module>
        long_description = open(os.path.join(base_path, 'README.rst')).read()
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1383: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/featureforge/setup.py", line 11, in <module>

    long_description = open(os.path.join(base_path, 'README.rst')).read()

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1383: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/featureforge
Storing debug log for failure in /root/.pip/pip.log

**Comment by jmansilla** [comment]
delgesu1745: your issues is about installing FeatureForge https://github.com/machinalis/featureforge which is one of the IEPY dependencies, and its related with your python not been able to work with unicode characters.

Can you try in your shell to configure your environment like this
export LANG=en_US.UTF-8
and retry?

**Comment by jmansilla** [comment]
Respect the issue with six, it's solved on develop now.
