### ISSUE TITLE
error in preprocessing with a different pipeline

### ISSUE THREAD

**Issue by ezesalta** [machinalis/iepy#89]
I change the pipeline in preprocess:
```pipeline = PreProcessPipeline([
        TokenizeSentencerRunner(),
        CombinedNERRunner([
            DateNERRunner(),
            PersonNERRunner(),
        ], override=True)
    ], docs)```

running bin/preprocess.py have the following errors:

```Starting preprocessing step <iepy.preprocess.tokenizer.TokenizeSentencerRunner object at 0x7fc7a8c323c8>
Traceback (most recent call last):
  File "bin/preprocess.py", line 105, in <module>
    start_preprocess(all_docs, increment_ner)
  File "bin/preprocess.py", line 60, in start_preprocess
    pipeline.process_everything()
  File "/home/ezequiel/.virtualenvs/pln-2015/lib/python3.4/site-packages/iepy/preprocess/pipeline.py", line 52, in process_everything
    self.process_step_in_batch(runner)
  File "/home/ezequiel/.virtualenvs/pln-2015/lib/python3.4/site-packages/iepy/preprocess/pipeline.py", line 41, in process_step_in_batch
    docs = self.documents.get_documents_lacking_preprocess(runner.step)
AttributeError: 'QuerySet' object has no attribute 'get_documents_lacking_preprocess'```

**Comment by jmansilla** [comment]
Shall be part of next 0.9.5 release
